data = [
    {'name': 'Instagram', 'follower_count': 670, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 625, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 500, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 429, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 400, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 397, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 364, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 319, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 311, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 306, 'description': 'Sportswear multinational', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 293, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 294, 'description': 'Model and reality TV star', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 283, 'description': 'Musician', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 283, 'description': 'Magazine and media company', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 268, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 253, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Nicki Minaj', 'follower_count': 228, 'description': 'Musician', 'country': 'Trinidad and Tobago'},
    {'name': 'Kourtney Kardashian', 'follower_count': 224, 'description': 'Reality TV star', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 217, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Neymar Jr', 'follower_count': 218, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Katy Perry', 'follower_count': 207, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 184, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 179, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 155, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Cardi B', 'follower_count': 168, 'description': 'Musician', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Demi Lovato', 'follower_count': 157, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 152, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Drake', 'follower_count': 145, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Chris Brown', 'follower_count': 145, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 139, 'description': 'Comedian and TV host', 'country': 'United States'},
    {'name': 'FC Barcelona', 'follower_count': 126, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Billie Eilish', 'follower_count': 110, 'description': 'Musician', 'country': 'United States'},
    {'name': 'UEFA Champions League', 'follower_count': 113, 'description': 'Club football competition', 'country': 'Europe'},
    {'name': 'Gal Gadot', 'follower_count': 108, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Kylian Mbappé', 'follower_count': 111, 'description': 'Footballer', 'country': 'France'},
    {'name': 'Vin Diesel', 'follower_count': 102, 'description': 'Actor', 'country': 'United States'},
    {'name': 'NASA', 'follower_count': 97, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Dua Lipa', 'follower_count': 88, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'NBA', 'follower_count': 86, 'description': 'Club basketball league', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower_count': 85, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Victoria Secret', 'follower_count': 76, 'description': 'Lingerie brand', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 87, 'description': 'Former footballer', 'country': 'United Kingdom'},
    {'name': 'Shawn Mendes', 'follower_count': 72, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Emma Watson', 'follower_count': 74, 'description': 'Actress and activist', 'country': 'United Kingdom'},
    {'name': 'Gigi Hadid', 'follower_count': 78, 'description': 'Model', 'country': 'United States'},
    {'name': 'Priyanka Chopra', 'follower_count': 90, 'description': 'Actress and musician', 'country': 'India'},
    {'name': 'Ronaldinho', 'follower_count': 75, 'description': 'Former footballer', 'country': 'Brazil'},
    {'name': 'Maluma', 'follower_count': 63, 'description': 'Musician', 'country': 'Colombia'}
]